### PR TITLE
Handle column widths and overflow

### PR DESCRIPTION
**Pull request by tbrisker**
This PR takes advantage of changes made by https://github.com/theforeman/foreman/pull/2789 to allow column width control and ellipsizing text.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Aplologies for the *very* slow reply @tbrisker. Just played around with this - it seems to me that it doesn;t really solve the overflow problem, it merely moves it (instead of my column_view column overflowing, now my action buttons overflow instead). Can we add ellipsis to the column maybe?

**Comment by discreet** [comment]
Just tested this patch in my lab environment running 1.11.2 and it does seem that this does not resolve the issue but just moved it to something else.

**Comment by tbrisker** [comment]
I opened https://github.com/theforeman/foreman/pull/3884 that should fix the issue with this PR allowing un-breaking this plugin.

**Comment by GregSutcliffe** [comment]
Along with the core PR, seems to work great! Merged as 9ad8de5, ty @tbrisker!

I'll get a new release out shortly (so that the plugin works with 1.13), but the core commit is slated for 1.13.1 so users should be aware that the UI fix won't happen until then.

**Comment by discreet** [comment]
Awesome! Can't thank you enough for this @tbrisker

**Comment by GregSutcliffe** [comment]
For those following this, 1.13.1 isout now, so this should all be working again. Thanks again @tbrisker!

**Pull request closed without merging**
